### ISSUE TITLE
need help installing 

### ISSUE THREAD

**Issue by litchiyan** [capitalone/acronym-decoder#37]
hey guys, former c1 associates here. tow questions:
1. is this the code base for slurp?
2. having below error when running npm install
npm ERR! code 1
npm ERR! path /Users/lyan/workspace/acronym-decoder/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/Cellar/node/17.2.0/bin/node /Users/lyan/workspace/acronym-decoder/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/Cellar/node/17.2.0/bin/node',
npm ERR! gyp verb cli   '/Users/lyan/workspace/acronym-decoder/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]

**Comment by amadib** [comment]
Hello @litchiyan - what version of node are you running?

**Comment by litchiyan** [comment]
➜  ~ node -v
v17.2.0

**Comment by amadib** [comment]
do you get the same issue downgrading?

**Comment by litchiyan** [comment]
What version is recommended?

**Comment by amadib** [comment]
Try version running with node v8. You may end up needing to also rebuild your `node-sass` (run the following command: `npm rebuild node-sass --force`). Let us know what happens.

**Comment by litchiyan** [comment]
@amadib still having issues install. is it possible to set up a quick call? thank you so much in advance!

**Comment by amadib** [comment]
Hello, @litchiyan - sorry for the delay. Can you try with the updated version of the acronym decoder and let us know if you experience any issues?

**Comment by amadib** [comment]
Closing this issue @litchiyan  - please feel free to reopen if you run into any issues.
