### ISSUE TITLE
Add acronym and distributing

### ISSUE THREAD

**Issue by hmajumdar** [capitalone/acronym-decoder#4]
Nice tool! What you guys think on giving the ability to add acronym and definition to the users? Also, when used within an organization, whats the best way to distribute it to large audience, should I be sending "dist" folder to everyone and ask them to load it to their chrome extension?

**Comment by baspartovi** [comment]
You can add that feature once you're hosting the content/data on a server and not on the actual extension which is the version we're offering here. We're leaving the hosting part up to you and we offer the ability within the extension. I think it's a great feature if you're planning to do that 👍 

In terms of distributing the extension within a company, you can certainly send the `dist` folder to users but that's not what i recommend. 
Instead try packaging and signing the `dist` folder by using what chrome already offers. You can go to `chrome://extensions` on your chrome browser and you should see the `Pack extension` button on top left. Create a new signing key for your extension (keep it safe and don't lose it) and then try using the internal app store for your company to distribute it or send the generated `.crx` file to your users. 

I recommend looking at this doc for more info: https://developer.chrome.com/extensions/hosting
